Map<String, String> engToEn = {
  'almonds': 'Almonds',
  'apple': 'Apple',
  'arhar': 'Arhar',
  'bajra': 'Bajra',
  'banana': 'Banana',
  'blackPepper': 'Black Pepper',
  'cashewnut': 'Cashewnut',
  'castorSeed': 'Castor Seed',
  'chillies': 'Chillies',
  'coffee': 'Coffee',
  'cottonSeed': 'Cotton Seed',
  'garlic': 'Garlic',
  'gram': 'Gram',
  'groundnut': 'Groundnut',
  'jowar': 'Jowar',
  'jute': 'Jute',
  'maize': 'Maize',
  'masoor': 'Masoor',
  'moong': 'Moong',
  'mustard': 'Mustard',
  'onion': 'Onion',
  'orange': 'Orange',
  'potato': 'Potato',
  'ragi': 'Ragi',
  'soyabean': 'Soyabean',
  'sunflowerSeed': 'Sunflower Seed',
  'tea': 'Tea',
  'tomato': 'Tomato',
  'urad': 'Urad',
  'walnuts': 'Walnuts',
  'wheat': 'Wheat',
  'krishiMitra': 'Krishi Mitra',
  'welcomeToKrishiMitra': 'Welcome to Krishi mitra',
  'proceed': 'Proceed',
  'cropPrice': 'Crop Price',
  'cropDemand': 'Crop Demand',
  'pestDiseaseDetection': 'Pest & Disease Detection',
  'settings': 'Settings',
  'selectState': 'Select State',
  'cropsIn': 'Crops in',
  'thisMonth': 'This Month',
  'nextMonth': 'Next Month',
  'priceTrend': 'Price Trend',
  'demandTrend': 'Demand Trend',
  'predictionPeriod': 'Prediction Period',
  'next3Months': 'Next 3 Months',
  'next6Months': 'Next 6 Months',
  'next1Year': 'Next 1 Year',
  'past6MonthsPrices': 'Past 6 Months Prices',
  'futurePricePredictions': 'Future Price Predictions',
  'past6MonthsDemand': 'Past 6 Months Demand',
  'futureDemandPredictions': 'Future Demand Predictions',
  'january': 'January',
  'february': 'February',
  'march': 'March',
  'april': 'April',
  'may': 'May',
  'june': 'June',
  'july': 'July',
  'august': 'August',
  'september': 'September',
  'october': 'October',
  'november': 'November',
  'language': 'Language',
  'noCropData': 'No crop data available for this state.',
  'noPriceData': 'No price data available to display.',
  'noDemandData': 'No demand data available to display.',
  'disease': 'Disease',
  'treatment': 'Treatment',
  'uploadPhoto': 'Upload Photo',
  'noImageSelected': 'No image selected',
  'andhraPradesh': 'Andhra Pradesh',
  'arunachalPradesh': 'Arunachal Pradesh',
  'assam': 'Assam',
  'bihar': 'Bihar',
  'chhattisgarh': 'Chhattisgarh',
  'goa': 'Goa',
  'gujarat': 'Gujarat',
  'haryana': 'Haryana',
  'himachalPradesh': 'Himachal Pradesh',
  'jharkhand': 'Jharkhand',
  'karnataka': 'Karnataka',
  'kerala': 'Kerala',
  'madhaPradesh': 'Madhya Pradesh',
  'maharashtra': 'Maharashtra',
  'manipur': 'Manipur',
  'meghalaya': 'Meghalaya',
  'moizoram': 'Mizoram',
  'nagaland': 'Nagaland',
  'odisha': 'Odisha',
  'punjab': 'Punjab',
  'rajasthan': 'Rajasthan',
  'sikkim': 'Sikkim',
  'tamilNadu': 'Tamil Nadu',
  'telangana': 'Telangana',
  'tripura': 'Tripura',
  'uttarPradesh': 'Uttar Pradesh',
  'uttarakhand': 'Uttarakhand',
  'westBengal': 'West Bengal',
};

Map<String, String> engToHi = {
  'almonds': 'बादाम',
  'apple': 'सेब',
  'arhar': 'अरहर',
  'bajra': 'बाजरे',
  'banana': 'केला',
  'blackPepper': 'काली मिर्च',
  'cashewnut': 'काजू',
  'castorSeed': 'अरंडी के बीज',
  'chillies': 'मिर्च',
  'coffee': 'कॉफी',
  'cottonSeed': 'कपास बीज',
  'garlic': 'लहसुन',
  'gram': 'ग्राम',
  'groundnut': 'मूंगफली',
  'jowar': 'ज्वार',
  'jute': 'जूट',
  'maize': 'मक्का',
  'masoor': 'मसूर',
  'moong': 'मूंग',
  'mustard': 'सरसों',
  'onion': 'प्याज',
  'orange': 'नारंगी',
  'potato': 'आलू',
  'ragi': 'रागी',
  'soyabean': 'सोया बीन',
  'sunflowerSeed': 'सूरजमुखी के बीज',
  'tea': 'चाय',
  'tomato': 'टमाटर',
  'urad': 'उड़द',
  'walnuts': 'अखरोट',
  'wheat': 'गेहूँ',
  'krishiMitra': 'कृषि मित्र',
  'welcomeToKrishiMitra': 'कृषि मित्र में आपका स्वागत है',
  'proceed': 'आगे बढ़ना',
  'cropPrice': 'फसल मूल्य',
  'cropDemand': 'फसल की मांग',
  'pestDiseaseDetection': 'कीट एवं रोग का पता लगाना',
  'settings': 'सेटिंग्स',
  'selectState': 'राज्य चुनें',
  'cropsIn': 'फसलें',
  'thisMonth': 'इस महीने',
  'nextMonth': 'अगले महीने',
  'priceTrend': 'मूल्य प्रवृत्ति',
  'demandTrend': 'मांग का रुझान',
  'predictionPeriod': 'भविष्यवाणी अवधि',
  'next3Months': 'अगले 3 महीने',
  'next6Months': 'अगले 6 महीने',
  'next1Year': 'अगला 1 वर्ष',
  'past6MonthsPrices': 'पिछले 6 महीनों की कीमतें',
  'futurePricePredictions': 'भावी मूल्य पूर्वानुमान',
  'past6MonthsDemand': 'पिछले 6 महीने की मांग',
  'futureDemandPredictions': 'भविष्य की मांग का पूर्वानुमान',
  'january': 'जनवरी',
  'february': 'फ़रवरी',
  'march': 'मार्च',
  'april': 'अप्रैल',
  'may': 'मई',
  'june': 'जून',
  'july': 'जुलाई',
  'august': 'अगस्त',
  'september': 'सितम्बर',
  'october': 'अक्टूबर',
  'november': 'नवंबर',
  'language': 'भाषा',
  'noCropData': 'इस राज्य के लिए कोई फसल डेटा उपलब्ध नहीं है।',
  'noPriceData': 'प्रदर्शित करने के लिए कोई मूल्य डेटा उपलब्ध नहीं है.',
  'noDemandData': 'प्रदर्शित करने के लिए कोई मांग डेटा उपलब्ध नहीं है।',
  'disease': 'बीमारी',
  'treatment': 'इलाज',
  'uploadPhoto': 'फोटो अपलोड करें',
  'noImageSelected': 'कोई छवि चयनित नहीं',
  'andhraPradesh': 'आंध्र प्रदेश',
  'arunachalPradesh': 'अरुणाचल प्रदेश',
  'assam': 'असम',
  'bihar': 'बिहार',
  'chhattisgarh': 'छत्तीसगढ',
  'goa': 'गोवा',
  'gujarat': 'गुजरात',
  'haryana': 'हरयाणा',
  'himachalPradesh': 'हिमाचल प्रदेश',
  'jharkhand': 'झारखंड',
  'karnataka': 'कर्नाटक',
  'kerala': 'केरल',
  'madhaPradesh': 'मध्य प्रदेश',
  'maharashtra': 'महाराष्ट्र',
  'manipur': 'मणिपुर',
  'meghalaya': 'मेघालय',
  'moizoram': 'मिजोरम',
  'nagaland': 'नगालैंड',
  'odisha': 'ओडिशा',
  'punjab': 'पंजाब',
  'rajasthan': 'राजस्थान',
  'sikkim': 'सिक्किम',
  'tamilNadu': 'तमिलनाडु',
  'telangana': 'तेलंगाना',
  'tripura': 'त्रिपुरा',
  'uttarPradesh': 'उतार प्रदेश।',
  'uttarakhand': 'उत्तराखंड',
  'westBengal': 'पश्चिम बंगाल',
};

Map<String, String> engToTa = {
  'almonds': 'பாதாம்',
  'apple': 'ஆப்பிள்',
  'arhar': 'அர்ஹர்',
  'bajra': 'பஜ்ரா',
  'banana': 'வாழைப்பழம்',
  'blackPepper': 'கருப்பு மிளகு',
  'cashewnut': 'முந்திரி',
  'castorSeed': 'ஆமணக்கு விதை',
  'chillies': 'மிளகாய்',
  'coffee': 'காபி',
  'cottonSeed': 'பருத்தி விதை',
  'garlic': 'பூண்டு',
  'gram': 'கிராம்',
  'groundnut': 'நிலக்கடலை',
  'jowar': 'ஜோவர்',
  'jute': 'சணல்',
  'maize': 'சோளம்',
  'masoor': 'மசூர்',
  'moong': 'மூங்',
  'mustard': 'கடுகு',
  'onion': 'வெங்காயம்',
  'orange': 'ஆரஞ்சு',
  'potato': 'உருளைக்கிழங்கு',
  'ragi': 'ராகி',
  'soyabean': 'சோயாபீன்',
  'sunflowerSeed': 'சூரியகாந்தி விதை',
  'tea': 'தேநீர்',
  'tomato': 'தக்காளி',
  'urad': 'உரட்',
  'walnuts': 'அக்ரூட் பருப்புகள்',
  'wheat': 'கோதுமை',
  'krishiMitra': 'கிருஷி மித்ரா',
  'welcomeToKrishiMitra': 'கிருஷி மித்ராவை வரவேற்கிறோம்',
  'proceed': 'தொடரவும்',
  'cropPrice': 'பயிர் விலை',
  'cropDemand': 'பயிர் தேவை',
  'pestDiseaseDetection': 'பூச்சி மற்றும் நோய் கண்டறிதல்',
  'settings': 'அமைப்புகள்',
  'selectState': 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
  'cropsIn': 'பயிர்கள்',
  'thisMonth': 'இந்த மாதம்',
  'nextMonth': 'அடுத்த மாதம்',
  'priceTrend': 'விலை போக்கு',
  'demandTrend': 'தேவைப் போக்கு',
  'predictionPeriod': 'கணிப்பு காலம்',
  'next3Months': 'அடுத்த 3 மாதங்கள்',
  'next6Months': 'அடுத்த 6 மாதங்கள்',
  'next1Year': 'அடுத்த 1 வருடம்',
  'past6MonthsPrices': 'கடந்த 6 மாத விலைகள்',
  'futurePricePredictions': 'எதிர்கால விலை கணிப்புகள்',
  'past6MonthsDemand': 'கடந்த 6 மாத கோரிக்கை',
  'futureDemandPredictions': 'எதிர்கால தேவை கணிப்புகள்',
  'january': 'ஜனவரி',
  'february': 'பிப்ரவரி',
  'march': 'மார்ச்',
  'april': 'ஏப்ரல்',
  'may': 'மே',
  'june': 'ஜூன்',
  'july': 'ஜூலை',
  'august': 'ஆகஸ்ட்',
  'september': 'செப்டம்பர்',
  'october': 'அக்டோபர்',
  'november': 'நவம்பர்',
  'language': 'மொழி',
  'noCropData': 'இந்த மாநிலத்திற்கான பயிர் தரவு எதுவும் கிடைக்கவில்லை.',
  'noPriceData': 'காண்பிக்க விலை தரவு எதுவும் இல்லை.',
  'noDemandData': 'காண்பிக்க டிமாண்ட் டேட்டா எதுவும் இல்லை.',
  'disease': 'நோய்',
  'treatment': 'சிகிச்சை',
  'uploadPhoto': 'புகைப்படத்தைப் பதிவேற்றவும்',
  'noImageSelected': 'படம் எதுவும் தேர்ந்தெடுக்கப்படவில்லை',
  'andhraPradesh': 'ஆந்திரப் பிரதேசம்',
  'arunachalPradesh': 'அருணாச்சல பிரதேசம்',
  'assam': 'அசாம்',
  'bihar': 'பீகார்',
  'chhattisgarh': 'சத்தீஸ்கர்',
  'goa': 'கோவா',
  'gujarat': 'குஜராத்',
  'haryana': 'ஹரியானா',
  'himachalPradesh': 'ஹிமாச்சல பிரதேசம்',
  'jharkhand': 'ஜார்கண்ட்',
  'karnataka': 'கர்நாடகா',
  'kerala': 'கேரளா',
  'madhaPradesh': 'மத்திய பிரதேசம்',
  'maharashtra': 'மகாராஷ்டிரா',
  'manipur': 'மணிப்பூர்',
  'meghalaya': 'மேகாலயா',
  'moizoram': 'மிசோரம்',
  'nagaland': 'நாகாலாந்து',
  'odisha': 'ஒடிசா',
  'punjab': 'பஞ்சாப்',
  'rajasthan': 'ராஜஸ்தான்',
  'sikkim': 'சிக்கிம்',
  'tamilNadu': 'தமிழ்நாடு',
  'telangana': 'தெலுங்கானா',
  'tripura': 'திரிபுரா',
  'uttarPradesh': 'உத்தரப்பிரதேசம்',
  'uttarakhand': 'உத்தரகாண்ட்',
  'westBengal': 'மேற்கு வங்காளம்',
};

Map<String, String> engToTe = {
  'almonds': 'బాదం',
  'apple': 'ఆపిల్',
  'arhar': 'అర్హర్',
  'bajra': 'బజ్రా',
  'banana': 'అరటిపండు',
  'blackPepper': 'నల్ల మిరియాలు',
  'cashewnut': 'జీడిపప్పు',
  'castorSeed': 'కాస్టర్ సీడ్',
  'chillies': 'మిరపకాయలు',
  'coffee': 'కాఫీ',
  'cottonSeed': 'పత్తి విత్తనం',
  'garlic': 'వెల్లుల్లి',
  'gram': 'గ్రాము',
  'groundnut': 'వేరుశనగ',
  'jowar': 'జోవర్',
  'jute': 'జనపనార',
  'maize': 'మొక్కజొన్న',
  'masoor': 'మసూర్',
  'moong': 'మూంగ్',
  'mustard': 'ఆవాలు',
  'onion': 'ఉల్లిపాయ',
  'orange': 'నారింజ రంగు',
  'potato': 'బంగాళదుంప',
  'ragi': 'రాగి',
  'soyabean': 'సోయాబీన్',
  'sunflowerSeed': 'సన్‌ఫ్లవర్ సీడ్',
  'tea': 'టీ',
  'tomato': 'టొమాటో',
  'urad': 'ఉరద్',
  'walnuts': 'అక్రోట్లను',
  'wheat': 'గోధుమలు',
  'krishiMitra': 'కృషి మిత్ర',
  'welcomeToKrishiMitra': 'కృషి మిత్రకు స్వాగతం',
  'proceed': 'కొనసాగండి',
  'cropPrice': 'పంట ధర',
  'cropDemand': 'పంట డిమాండ్',
  'pestDiseaseDetection': 'తెగులు & వ్యాధి గుర్తింపు',
  'settings': 'సెట్టింగ్‌లు',
  'selectState': 'రాష్ట్రం ఎంచుకోండి',
  'cropsIn': 'లో పంటలు',
  'thisMonth': 'ఈ నెల',
  'nextMonth': 'వచ్చే నెల',
  'priceTrend': 'ధర ట్రెండ్',
  'demandTrend': 'డిమాండ్ ట్రెండ్',
  'predictionPeriod': 'అంచనా కాలం',
  'next3Months': 'తదుపరి 3 నెలలు',
  'next6Months': 'తదుపరి 6 నెలలు',
  'next1Year': 'తదుపరి 1 సంవత్సరం',
  'past6MonthsPrices': 'గత 6 నెలల ధరలు',
  'futurePricePredictions': 'భవిష్యత్ ధర అంచనాలు',
  'past6MonthsDemand': 'గత 6 నెలల డిమాండ్',
  'futureDemandPredictions': 'భవిష్యత్ డిమాండ్ అంచనాలు',
  'january': 'జనవరి',
  'february': 'ఫిబ్రవరి',
  'march': 'మార్చి',
  'april': 'ఏప్రిల్',
  'may': 'మే',
  'june': 'జూన్',
  'july': 'జూలై',
  'august': 'ఆగస్టు',
  'september': 'సెప్టెంబర్',
  'october': 'అక్టోబర్',
  'november': 'నవంబర్',
  'language': 'భాష',
  'noCropData': 'ఈ రాష్ట్రం కోసం క్రాప్ డేటా అందుబాటులో లేదు.',
  'noPriceData': 'ప్రదర్శించడానికి ధర డేటా అందుబాటులో లేదు.',
  'noDemandData': 'ప్రదర్శించడానికి డిమాండ్ డేటా అందుబాటులో లేదు.',
  'disease': 'వ్యాధి',
  'treatment': 'చికిత్స',
  'uploadPhoto': 'ఫోటోను అప్‌లోడ్ చేయండి',
  'noImageSelected': 'చిత్రం ఏదీ ఎంచుకోబడలేదు',
  'andhraPradesh': 'ఆంధ్ర ప్రదేశ్',
  'arunachalPradesh': 'అరుణాచల్ ప్రదేశ్',
  'assam': 'అస్సాం',
  'bihar': 'బీహార్',
  'chhattisgarh': 'ఛత్తీస్‌గఢ్',
  'goa': 'గోవా',
  'gujarat': 'గుజరాత్',
  'haryana': 'హర్యానా',
  'himachalPradesh': 'హిమాచల్ ప్రదేశ్',
  'jharkhand': 'జార్ఖండ్',
  'karnataka': 'కర్ణాటక',
  'kerala': 'కేరళ',
  'madhaPradesh': 'మధ్యప్రదేశ్',
  'maharashtra': 'మహారాష్ట్ర',
  'manipur': 'మణిపూర్',
  'meghalaya': 'మేఘాలయ',
  'moizoram': 'మిజోరం',
  'nagaland': 'నాగాలాండ్',
  'odisha': 'ఒడిశా',
  'punjab': 'పంజాబ్',
  'rajasthan': 'రాజస్థాన్',
  'sikkim': 'సిక్కిం',
  'tamilNadu': 'తమిళనాడు',
  'telangana': 'తెలంగాణ',
  'tripura': 'త్రిపుర',
  'uttarPradesh': 'ఉత్తర ప్రదేశ్',
  'uttarakhand': 'ఉత్తరాఖండ్',
  'westBengal': 'పశ్చిమ బెంగాల్',
};

Map<String, String> engToBn = {
  'almonds': 'বাদাম',
  'apple': 'আপেল',
  'arhar': 'আরহার',
  'bajra': 'বজরা',
  'banana': 'কলা',
  'blackPepper': 'কালো মরিচ',
  'cashewnut': 'কাজুবাদাম',
  'castorSeed': 'ক্যাস্টর বীজ',
  'chillies': 'মরিচ',
  'coffee': 'কফি',
  'cottonSeed': 'তুলা বীজ',
  'garlic': 'রসুন',
  'gram': 'ছোলা',
  'groundnut': 'চিনাবাদাম',
  'jowar': 'জোয়ার',
  'jute': 'পাট',
  'maize': 'ভুট্টা',
  'masoor': 'মাসুর',
  'moong': 'মুং',
  'mustard': 'সরিষা',
  'onion': 'পেঁয়াজ',
  'orange': 'কমলা',
  'potato': 'আলু',
  'ragi': 'রাগী',
  'soyabean': 'সয়াবিন',
  'sunflowerSeed': 'সূর্যমুখী বীজ',
  'tea': 'চা',
  'tomato': 'টমেটো',
  'urad': 'উরদ',
  'walnuts': 'আখরোট',
  'wheat': 'গম',
  'krishiMitra': 'কৃষি মিত্র',
  'welcomeToKrishiMitra': 'কৃষি মিত্রে স্বাগতম',
  'proceed': 'এগিয়ে যান',
  'cropPrice': 'ফসলের দাম',
  'cropDemand': 'ফসলের চাহিদা',
  'pestDiseaseDetection': 'কীটপতঙ্গ ও রোগ নির্ণয়',
  'settings': 'সেটিংস',
  'selectState': 'রাজ্য নির্বাচন করুন',
  'cropsIn': 'মধ্যে ফসল',
  'thisMonth': 'এই মাসে',
  'nextMonth': 'পরের মাস',
  'priceTrend': 'মূল্য প্রবণতা',
  'demandTrend': 'চাহিদা প্রবণতা',
  'predictionPeriod': 'ভবিষ্যদ্বাণীর সময়কাল',
  'next3Months': 'পরের ৩ মাস',
  'next6Months': 'পরের ৬ মাস',
  'next1Year': 'আগামী ১ বছর',
  'past6MonthsPrices': 'গত 6 মাসের দাম',
  'futurePricePredictions': 'ভবিষ্যতের মূল্য পূর্বাভাস',
  'past6MonthsDemand': 'গত 6 মাসের চাহিদা',
  'futureDemandPredictions': 'ভবিষ্যতের চাহিদা পূর্বাভাস',
  'january': 'জানুয়ারি',
  'february': 'ফেব্রুয়ারি',
  'march': 'মার্চ',
  'april': 'এপ্রিল',
  'may': 'মে',
  'june': 'জুন',
  'july': 'জুলাই',
  'august': 'আগস্ট',
  'september': 'সেপ্টেম্বর',
  'october': 'অক্টোবর',
  'november': 'নভেম্বর',
  'language': 'ভাষা',
  'noCropData': 'এই রাজ্যের জন্য কোনো ক্রপ ডেটা উপলব্ধ নেই৷',
  'noPriceData': 'প্রদর্শনের জন্য কোনো মূল্য ডেটা উপলব্ধ নেই৷',
  'noDemandData': 'ডিসপ্লে করার জন্য কোনো ডিমান্ড ডেটা পাওয়া যায় না।',
  'disease': 'রোগ',
  'treatment': 'চিকিৎসা',
  'uploadPhoto': 'ছবি আপলোড করুন',
  'noImageSelected': 'কোনো ছবি নির্বাচন করা হয়নি',
  'andhraPradesh': 'অন্ধ্রপ্রদেশ',
  'arunachalPradesh': 'অরুণাচল প্রদেশ',
  'assam': 'আসাম',
  'bihar': 'বিহার',
  'chhattisgarh': 'ছত্তিশগড়',
  'goa': 'গোয়া',
  'gujarat': 'গুজরাট',
  'haryana': 'হরিয়ানা',
  'himachalPradesh': 'হিমাচল প্রদেশ',
  'jharkhand': 'ঝাড়খণ্ড',
  'karnataka': 'কর্ণাটক',
  'kerala': 'কেরালা',
  'madhaPradesh': 'মধ্যপ্রদেশ',
  'maharashtra': 'মহারাষ্ট্র',
  'manipur': 'মণিপুর',
  'meghalaya': 'মেঘালয়',
  'moizoram': 'মিজোরাম',
  'nagaland': 'নাগাল্যান্ড',
  'odisha': 'ওড়িশা',
  'punjab': 'পাঞ্জাব',
  'rajasthan': 'রাজস্থান',
  'sikkim': 'সিকিম',
  'tamilNadu': 'তামিলনাড়ু',
  'telangana': 'তেলেঙ্গানা',
  'tripura': 'ত্রিপুরা',
  'uttarPradesh': 'উত্তরপ্রদেশ',
  'uttarakhand': 'উত্তরাখণ্ড',
  'westBengal': 'পশ্চিমবঙ্গ',
};

Map<String, String> engToGu = {
  'almonds': 'બદામ',
  'apple': 'એપલ',
  'arhar': 'અરહર',
  'bajra': 'બાજરી',
  'banana': 'બનાના',
  'blackPepper': 'કાળા મરી',
  'cashewnut': 'કાજુ',
  'castorSeed': 'એરંડાનું બીજ',
  'chillies': 'મરચાં',
  'coffee': 'કોફી',
  'cottonSeed': 'કપાસનું બીજ',
  'garlic': 'લસણ',
  'gram': 'ગ્રામ',
  'groundnut': 'મગફળી',
  'jowar': 'જુવાર',
  'jute': 'જ્યુટ',
  'maize': 'મકાઈ',
  'masoor': 'મસૂર',
  'moong': 'મૂંગ',
  'mustard': 'સરસવ',
  'onion': 'ડુંગળી',
  'orange': 'નારંગી',
  'potato': 'બટાકા',
  'ragi': 'રાગી',
  'soyabean': 'સોયાબીન',
  'sunflowerSeed': 'સૂર્યમુખી બીજ',
  'tea': 'ચા',
  'tomato': 'ટામેટા',
  'urad': 'અડદ',
  'walnuts': 'અખરોટ',
  'wheat': 'ઘઉં',
  'krishiMitra': 'કૃષિ મિત્ર',
  'welcomeToKrishiMitra': 'કૃષિ મિત્રમાં આપનું સ્વાગત છે',
  'proceed': 'આગળ વધો',
  'cropPrice': 'પાકની કિંમત',
  'cropDemand': 'પાકની માંગ',
  'pestDiseaseDetection': 'જંતુ અને રોગની તપાસ',
  'settings': 'સેટિંગ્સ',
  'selectState': 'રાજ્ય પસંદ કરો',
  'cropsIn': 'માં પાક',
  'thisMonth': 'આ મહિને',
  'nextMonth': 'આગામી મહિને',
  'priceTrend': 'ભાવ વલણ',
  'demandTrend': 'માંગ વલણ',
  'predictionPeriod': 'આગાહીનો સમયગાળો',
  'next3Months': 'આગામી 3 મહિના',
  'next6Months': 'આગામી 6 મહિના',
  'next1Year': 'આગામી 1 વર્ષ',
  'past6MonthsPrices': 'છેલ્લા 6 મહિનાની કિંમતો',
  'futurePricePredictions': 'ભાવિ ભાવ અનુમાનો',
  'past6MonthsDemand': 'છેલ્લા 6 મહિનાની માંગ',
  'futureDemandPredictions': 'ભાવિ માંગ અનુમાનો',
  'january': 'જાન્યુઆરી',
  'february': 'ફેબ્રુઆરી',
  'march': 'માર્ચ',
  'april': 'એપ્રિલ',
  'may': 'મે',
  'june': 'જૂન',
  'july': 'જુલાઈ',
  'august': 'ઓગસ્ટ',
  'september': 'સપ્ટેમ્બર',
  'october': 'ઓક્ટોબર',
  'november': 'નવેમ્બર',
  'language': 'ભાષા',
  'noCropData': 'આ રાજ્ય માટે કોઈ પાક ડેટા ઉપલબ્ધ નથી.',
  'noPriceData': 'પ્રદર્શિત કરવા માટે કોઈ કિંમત ડેટા ઉપલબ્ધ નથી.',
  'noDemandData': 'પ્રદર્શિત કરવા માટે કોઈ માંગ ડેટા ઉપલબ્ધ નથી.',
  'disease': 'રોગ',
  'treatment': 'સારવાર',
  'uploadPhoto': 'ફોટો અપલોડ કરો',
  'noImageSelected': 'કોઈ છબી પસંદ કરી નથી',
  'andhraPradesh': 'આંધ્ર પ્રદેશ',
  'arunachalPradesh': 'અરુણાચલ પ્રદેશ',
  'assam': 'આસામ',
  'bihar': 'બિહાર',
  'chhattisgarh': 'છત્તીસગઢ',
  'goa': 'ગોવા',
  'gujarat': 'ગુજરાત',
  'haryana': 'હરિયાણા',
  'himachalPradesh': 'હિમાચલ પ્રદેશ',
  'jharkhand': 'ઝારખંડ',
  'karnataka': 'કર્ણાટક',
  'kerala': 'કેરળ',
  'madhaPradesh': 'મધ્યપ્રદેશ',
  'maharashtra': 'મહારાષ્ટ્ર',
  'manipur': 'મણિપુર',
  'meghalaya': 'મેઘાલય',
  'moizoram': 'મિઝોરમ',
  'nagaland': 'નાગાલેન્ડ',
  'odisha': 'ઓડિશા',
  'punjab': 'પંજાબ',
  'rajasthan': 'રાજસ્થાન',
  'sikkim': 'સિક્કિમ',
  'tamilNadu': 'તમિલનાડુ',
  'telangana': 'તેલંગાણા',
  'tripura': 'ત્રિપુરા',
  'uttarPradesh': 'ઉત્તર પ્રદેશ',
  'uttarakhand': 'ઉત્તરાખંડ',
  'westBengal': 'પશ્ચિમ બંગાળ',
};

Map<String, String> engToMr = {
  'almonds': 'बदाम',
  'apple': 'सफरचंद',
  'arhar': 'अरहर',
  'bajra': 'बाजरी',
  'banana': 'केळी',
  'blackPepper': 'काळी मिरी',
  'cashewnut': 'काजू',
  'castorSeed': 'एरंडेल बी',
  'chillies': 'मिरच्या',
  'coffee': 'कॉफी',
  'cottonSeed': 'कापूस बियाणे',
  'garlic': 'लसूण',
  'gram': 'हरभरा',
  'groundnut': 'भुईमूग',
  'jowar': 'ज्वारी',
  'jute': 'ज्यूट',
  'maize': 'मका',
  'masoor': 'मसूर',
  'moong': 'मूग',
  'mustard': 'मोहरी',
  'onion': 'कांदा',
  'orange': 'केशरी',
  'potato': 'बटाटा',
  'ragi': 'रागी',
  'soyabean': 'सोयाबीन',
  'sunflowerSeed': 'सूर्यफूल बियाणे',
  'tea': 'चहा',
  'tomato': 'टोमॅटो',
  'urad': 'उडीद',
  'walnuts': 'अक्रोड',
  'wheat': 'गहू',
  'krishiMitra': 'कृषी मित्र',
  'welcomeToKrishiMitra': 'कृषी मित्रामध्ये आपले स्वागत आहे',
  'proceed': 'पुढे जा',
  'cropPrice': 'पिकाची किंमत',
  'cropDemand': 'पीक मागणी',
  'pestDiseaseDetection': 'कीटक आणि रोग शोधणे',
  'settings': 'सेटिंग्ज',
  'selectState': 'राज्य निवडा',
  'cropsIn': 'मध्ये पिके',
  'thisMonth': 'या महिन्यात',
  'nextMonth': 'पुढचा महिना',
  'priceTrend': 'किंमत ट्रेंड',
  'demandTrend': 'मागणी कल',
  'predictionPeriod': 'अंदाज कालावधी',
  'next3Months': 'पुढील ३ महिने',
  'next6Months': 'पुढील ६ महिने',
  'next1Year': 'पुढील 1 वर्ष',
  'past6MonthsPrices': 'मागील 6 महिन्यांच्या किमती',
  'futurePricePredictions': 'भविष्यातील किंमत अंदाज',
  'past6MonthsDemand': 'मागील 6 महिन्यांची मागणी',
  'futureDemandPredictions': 'भविष्यातील मागणी अंदाज',
  'january': 'जानेवारी',
  'february': 'फेब्रुवारी',
  'march': 'मार्च',
  'april': 'एप्रिल',
  'may': 'मे',
  'june': 'जून',
  'july': 'जुलै',
  'august': 'ऑगस्ट',
  'september': 'सप्टेंबर',
  'october': 'ऑक्टोबर',
  'november': 'नोव्हेंबर',
  'language': 'भाषा',
  'noCropData': 'या राज्यासाठी कोणताही पीक डेटा उपलब्ध नाही.',
  'noPriceData': 'प्रदर्शित करण्यासाठी किंमत डेटा उपलब्ध नाही.',
  'noDemandData': 'प्रदर्शित करण्यासाठी कोणताही मागणी डेटा उपलब्ध नाही.',
  'disease': 'रोग',
  'treatment': 'उपचार',
  'uploadPhoto': 'फोटो अपलोड करा',
  'noImageSelected': 'कोणतीही प्रतिमा निवडलेली नाही',
  'andhraPradesh': 'आंध्र प्रदेश',
  'arunachalPradesh': 'अरुणाचल प्रदेश',
  'assam': 'आसाम',
  'bihar': 'बिहार',
  'chhattisgarh': 'छत्तीसगड',
  'goa': 'गोवा',
  'gujarat': 'गुजरात',
  'haryana': 'हरियाणा',
  'himachalPradesh': 'हिमाचल प्रदेश',
  'jharkhand': 'झारखंड',
  'karnataka': 'कर्नाटक',
  'kerala': 'केरळ',
  'madhaPradesh': 'मध्य प्रदेश',
  'maharashtra': 'महाराष्ट्र',
  'manipur': 'मणिपूर',
  'meghalaya': 'मेघालय',
  'moizoram': 'मिझोराम',
  'nagaland': 'नागालँड',
  'odisha': 'ओडिशा',
  'punjab': 'पंजाब',
  'rajasthan': 'राजस्थान',
  'sikkim': 'सिक्कीम',
  'tamilNadu': 'तामिळनाडू',
  'telangana': 'तेलंगणा',
  'tripura': 'त्रिपुरा',
  'uttarPradesh': 'उत्तर प्रदेश',
  'uttarakhand': 'उत्तराखंड',
  'westBengal': 'पश्चिम बंगाल',
};

Map<String, String> engToPa = {
  'almonds': 'ਬਦਾਮ',
  'apple': 'ਐਪਲ',
  'arhar': 'ਅਰਹਰ',
  'bajra': 'ਬਾਜਰਾ',
  'banana': 'ਕੇਲਾ',
  'blackPepper': 'ਕਾਲੀ ਮਿਰਚ',
  'cashewnut': 'ਕਾਜੂ',
  'castorSeed': 'ਕੈਸਟਰ ਬੀਜ',
  'chillies': 'ਮਿਰਚ',
  'coffee': 'ਕਾਫੀ',
  'cottonSeed': 'ਕਪਾਹ ਬੀਜ',
  'garlic': 'ਲਸਣ',
  'gram': 'ਗ੍ਰਾਮ',
  'groundnut': 'ਮੂੰਗਫਲੀ',
  'jowar': 'ਜਵਾਰ',
  'jute': 'ਜੂਟ',
  'maize': 'ਮੱਕੀ',
  'masoor': 'ਮਸੂਰ',
  'moong': 'ਮੂੰਗ',
  'mustard': 'ਸਰ੍ਹੋਂ',
  'onion': 'ਪਿਆਜ',
  'orange': 'ਸੰਤਰਾ',
  'potato': 'ਆਲੂ',
  'ragi': 'ਰਾਗੀ',
  'soyabean': 'ਸੋਇਆਬੀਨ',
  'sunflowerSeed': 'ਸੂਰਜਮੁਖੀ ਦੇ ਬੀਜ',
  'tea': 'ਚਾਹ',
  'tomato': 'ਟਮਾਟਰ',
  'urad': 'ਉੜਦ',
  'walnuts': 'ਅਖਰੋਟ',
  'wheat': 'ਕਣਕ',
  'krishiMitra': 'ਕ੍ਰਿਸ਼ੀ ਮਿੱਤਰ',
  'welcomeToKrishiMitra': 'ਕ੍ਰਿਸ਼ੀ ਮਿੱਤਰਾ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
  'proceed': 'ਅੱਗੇ ਵਧੋ',
  'cropPrice': 'ਫਸਲ ਦੀ ਕੀਮਤ',
  'cropDemand': 'ਫਸਲ ਦੀ ਮੰਗ',
  'pestDiseaseDetection': 'ਕੀੜੇ ਅਤੇ ਰੋਗ ਦੀ ਖੋਜ',
  'settings': 'ਸੈਟਿੰਗਾਂ',
  'selectState': 'ਰਾਜ ਚੁਣੋ',
  'cropsIn': 'ਵਿੱਚ ਫਸਲ',
  'thisMonth': 'ਇਸ ਮਹੀਨੇ',
  'nextMonth': 'ਅਗਲੇ ਮਹੀਨੇ',
  'priceTrend': 'ਕੀਮਤ ਦਾ ਰੁਝਾਨ',
  'demandTrend': 'ਮੰਗ ਦਾ ਰੁਝਾਨ',
  'predictionPeriod': 'ਪੂਰਵ ਅਨੁਮਾਨ ਦੀ ਮਿਆਦ',
  'next3Months': 'ਅਗਲੇ 3 ਮਹੀਨੇ',
  'next6Months': 'ਅਗਲੇ 6 ਮਹੀਨੇ',
  'next1Year': 'ਅਗਲਾ 1 ਸਾਲ',
  'past6MonthsPrices': 'ਪਿਛਲੇ 6 ਮਹੀਨਿਆਂ ਦੀਆਂ ਕੀਮਤਾਂ',
  'futurePricePredictions': 'ਭਵਿੱਖ ਦੀਆਂ ਕੀਮਤਾਂ ਦੀਆਂ ਭਵਿੱਖਬਾਣੀਆਂ',
  'past6MonthsDemand': 'ਪਿਛਲੇ 6 ਮਹੀਨਿਆਂ ਦੀ ਮੰਗ',
  'futureDemandPredictions': 'ਭਵਿੱਖ ਦੀ ਮੰਗ ਦੀ ਭਵਿੱਖਬਾਣੀ',
  'january': 'ਜਨਵਰੀ',
  'february': 'ਫਰਵਰੀ',
  'march': 'ਮਾਰਚ',
  'april': 'ਅਪ੍ਰੈਲ',
  'may': 'ਮਈ',
  'june': 'ਜੂਨ',
  'july': 'ਜੁਲਾਈ',
  'august': 'ਅਗਸਤ',
  'september': 'ਸਤੰਬਰ',
  'october': 'ਅਕਤੂਬਰ',
  'november': 'ਨਵੰਬਰ',
  'language': 'ਭਾਸ਼ਾ',
  'noCropData': 'ਇਸ ਰਾਜ ਲਈ ਕੋਈ ਫਸਲ ਡੇਟਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
  'noPriceData': 'ਪ੍ਰਦਰਸ਼ਿਤ ਕਰਨ ਲਈ ਕੋਈ ਕੀਮਤ ਡੇਟਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
  'noDemandData': 'ਡਿਸਪਲੇ ਕਰਨ ਲਈ ਕੋਈ ਮੰਗ ਡੇਟਾ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
  'disease': 'ਰੋਗ',
  'treatment': 'ਇਲਾਜ',
  'uploadPhoto': 'ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
  'noImageSelected': 'ਕੋਈ ਚਿੱਤਰ ਨਹੀਂ ਚੁਣਿਆ ਗਿਆ',
  'andhraPradesh': 'ਆਂਧਰਾ ਪ੍ਰਦੇਸ਼',
  'arunachalPradesh': 'ਅਰੁਣਾਚਲ ਪ੍ਰਦੇਸ਼',
  'assam': 'ਅਸਾਮ',
  'bihar': 'ਬਿਹਾਰ',
  'chhattisgarh': 'ਛੱਤੀਸਗੜ੍ਹ',
  'goa': 'ਗੋਆ',
  'gujarat': 'ਗੁਜਰਾਤ',
  'haryana': 'ਹਰਿਆਣਾ',
  'himachalPradesh': 'ਹਿਮਾਚਲ ਪ੍ਰਦੇਸ਼',
  'jharkhand': 'ਝਾਰਖੰਡ',
  'karnataka': 'ਕਰਨਾਟਕ',
  'kerala': 'ਕੇਰਲ',
  'madhaPradesh': 'ਮੱਧ ਪ੍ਰਦੇਸ਼',
  'maharashtra': 'ਮਹਾਰਾਸ਼ਟਰ',
  'manipur': 'ਮਣੀਪੁਰ',
  'meghalaya': 'ਮੇਘਾਲਿਆ',
  'moizoram': 'ਮਿਜ਼ੋਰਮ',
  'nagaland': 'ਨਾਗਾਲੈਂਡ',
  'odisha': 'ਉੜੀਸਾ',
  'punjab': 'ਪੰਜਾਬ',
  'rajasthan': 'ਰਾਜਸਥਾਨ',
  'sikkim': 'ਸਿੱਕਮ',
  'tamilNadu': 'ਤਾਮਿਲਨਾਡੂ',
  'telangana': 'ਤੇਲੰਗਾਨਾ',
  'tripura': 'ਤ੍ਰਿਪੁਰਾ',
  'uttarPradesh': 'ਉੱਤਰ ਪ੍ਰਦੇਸ਼',
  'uttarakhand': 'ਉੱਤਰਾਖੰਡ',
  'westBengal': 'ਪੱਛਮੀ ਬੰਗਾਲ',
};

Map<String, String> engToUr = {
  'almonds': 'بادام',
  'apple': 'سیب',
  'arhar': 'ارہر',
  'bajra': 'باجرہ',
  'banana': 'کیلا',
  'blackPepper': 'کالی مرچ',
  'cashewnut': 'کاجو',
  'castorSeed': 'ارنڈ کا بیج',
  'chillies': 'مرچیں',
  'coffee': 'کافی',
  'cottonSeed': 'کپاس کا بیج',
  'garlic': 'لہسن',
  'gram': 'چنے',
  'groundnut': 'مونگ پھلی',
  'jowar': 'جوار',
  'jute': 'جوٹ',
  'maize': 'مکئی',
  'masoor': 'مسور',
  'moong': 'مونگ',
  'mustard': 'سرسوں',
  'onion': 'پیاز',
  'orange': 'کینو',
  'potato': 'آلو',
  'ragi': 'راگی',
  'soyabean': 'سویابین',
  'sunflowerSeed': 'سورج مکھی کا بیج',
  'tea': 'چائے',
  'tomato': 'ٹماٹر',
  'urad': 'اُڑد',
  'walnuts': 'اخروٹ',
  'wheat': 'گندم',
  'krishiMitra': 'کرشی مترا',
  'welcomeToKrishiMitra': 'کرشی مترا میں خوش آمدید',
  'proceed': 'آگے بڑھیں۔',
  'cropPrice': 'فصل کی قیمت',
  'cropDemand': 'فصل کی مانگ',
  'pestDiseaseDetection': 'کیڑوں اور بیماریوں کا پتہ لگانا',
  'settings': 'ترتیبات',
  'selectState': 'ریاست منتخب کریں۔',
  'cropsIn': 'میں فصلیں',
  'thisMonth': 'اس مہینے',
  'nextMonth': 'اگلا مہینہ',
  'priceTrend': 'قیمت کا رجحان',
  'demandTrend': 'مانگ کا رجحان',
  'predictionPeriod': 'پیشین گوئی کی مدت',
  'next3Months': 'اگلے 3 ماہ',
  'next6Months': 'اگلے 6 ماہ',
  'next1Year': 'اگلا 1 سال',
  'past6MonthsPrices': 'گزشتہ 6 ماہ کی قیمتیں۔',
  'futurePricePredictions': 'مستقبل کی قیمت کی پیشن گوئیاں',
  'past6MonthsDemand': 'گزشتہ 6 ماہ کا مطالبہ',
  'futureDemandPredictions': 'مستقبل کی مانگ کی پیشن گوئیاں',
  'january': 'جنوری',
  'february': 'فروری',
  'march': 'مارچ',
  'april': 'اپریل',
  'may': 'مئی',
  'june': 'جون',
  'july': 'جولائی',
  'august': 'اگست',
  'september': 'ستمبر',
  'october': 'اکتوبر',
  'november': 'نومبر',
  'language': 'زبان',
  'noCropData': 'اس ریاست کے لیے فصل کا کوئی ڈیٹا دستیاب نہیں ہے۔',
  'noPriceData': 'ڈسپلے کے لیے قیمت کا کوئی ڈیٹا دستیاب نہیں ہے۔',
  'noDemandData': 'ڈسپلے کے لیے کوئی ڈیمانڈ ڈیٹا دستیاب نہیں ہے۔',
  'disease': 'بیماری',
  'treatment': 'علاج',
  'uploadPhoto': 'تصویر اپ لوڈ کریں۔',
  'noImageSelected': 'کوئی تصویر منتخب نہیں کی گئی۔',
  'andhraPradesh': 'آندھرا پردیش',
  'arunachalPradesh': 'اروناچل پردیش',
  'assam': 'آسام',
  'bihar': 'بہار',
  'chhattisgarh': 'چھتیس گڑھ',
  'goa': 'گوا',
  'gujarat': 'گجرات',
  'haryana': 'ہریانہ',
  'himachalPradesh': 'ہماچل پردیش',
  'jharkhand': 'جھارکھنڈ',
  'karnataka': 'کرناٹک',
  'kerala': 'کیرالہ',
  'madhaPradesh': 'مدھیہ پردیش',
  'maharashtra': 'مہاراشٹر',
  'manipur': 'منی پور',
  'meghalaya': 'میگھالیہ',
  'moizoram': 'میزورم',
  'nagaland': 'ناگالینڈ',
  'odisha': 'اوڈیشہ',
  'punjab': 'پنجاب',
  'rajasthan': 'راجستھان',
  'sikkim': 'سکم',
  'tamilNadu': 'تمل ناڈو',
  'telangana': 'تلنگانہ',
  'tripura': 'تریپورہ',
  'uttarPradesh': 'اتر پردیش',
  'uttarakhand': 'اتراکھنڈ',
  'westBengal': 'مغربی بنگال',
};

Map<String, String> engToKn = {
  'almonds': 'ಬಾದಾಮಿ',
  'apple': 'ಆಪಲ್',
  'arhar': 'ಅರ್ಹರ್',
  'bajra': 'ಬಜ್ರಾ',
  'banana': 'ಬಾಳೆಹಣ್ಣು',
  'blackPepper': 'ಕಪ್ಪು ಮೆಣಸು',
  'cashewnut': 'ಗೋಡಂಬಿ',
  'castorSeed': 'ಕ್ಯಾಸ್ಟರ್ ಸೀಡ್',
  'chillies': 'ಮೆಣಸಿನಕಾಯಿಗಳು',
  'coffee': 'ಕಾಫಿ',
  'cottonSeed': 'ಹತ್ತಿ ಬೀಜ',
  'garlic': 'ಬೆಳ್ಳುಳ್ಳಿ',
  'gram': 'ಗ್ರಾಂ',
  'groundnut': 'ನೆಲಗಡಲೆ',
  'jowar': 'ಜೋವರ್',
  'jute': 'ಸೆಣಬು',
  'maize': 'ಮೆಕ್ಕೆಜೋಳ',
  'masoor': 'ಮಸೂರ್',
  'moong': 'ಮೂಂಗ್',
  'mustard': 'ಸಾಸಿವೆ',
  'onion': 'ಈರುಳ್ಳಿ',
  'orange': 'ಕಿತ್ತಳೆ',
  'potato': 'ಆಲೂಗಡ್ಡೆ',
  'ragi': 'ರಾಗಿ',
  'soyabean': 'ಸೋಯಾಬೀನ್',
  'sunflowerSeed': 'ಸೂರ್ಯಕಾಂತಿ ಬೀಜ',
  'tea': 'ಚಹಾ',
  'tomato': 'ಟೊಮೆಟೊ',
  'urad': 'ಉರಾದ್',
  'walnuts': 'ವಾಲ್ನಟ್ಸ್',
  'wheat': 'ಗೋಧಿ',
  'krishiMitra': 'ಕೃಷಿ ಮಿತ್ರ',
  'welcomeToKrishiMitra': 'ಕೃಷಿ ಮಿತ್ರ ಅವರಿಗೆ ಸ್ವಾಗತ',
  'proceed': 'ಮುಂದುವರೆಯಿರಿ',
  'cropPrice': 'ಬೆಳೆ ಬೆಲೆ',
  'cropDemand': 'ಬೆಳೆ ಬೇಡಿಕೆ',
  'pestDiseaseDetection': 'ಕೀಟ ಮತ್ತು ರೋಗ ಪತ್ತೆ',
  'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
  'selectState': 'ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
  'cropsIn': 'ಬೆಳೆಗಳು',
  'thisMonth': 'ಈ ತಿಂಗಳು',
  'nextMonth': 'ಮುಂದಿನ ತಿಂಗಳು',
  'priceTrend': 'ಬೆಲೆ ಪ್ರವೃತ್ತಿ',
  'demandTrend': 'ಬೇಡಿಕೆಯ ಪ್ರವೃತ್ತಿ',
  'predictionPeriod': 'ಮುನ್ಸೂಚನೆಯ ಅವಧಿ',
  'next3Months': 'ಮುಂದಿನ 3 ತಿಂಗಳು',
  'next6Months': 'ಮುಂದಿನ 6 ತಿಂಗಳು',
  'next1Year': 'ಮುಂದಿನ 1 ವರ್ಷ',
  'past6MonthsPrices': 'ಕಳೆದ 6 ತಿಂಗಳ ಬೆಲೆಗಳು',
  'futurePricePredictions': 'ಭವಿಷ್ಯದ ಬೆಲೆ ಮುನ್ಸೂಚನೆಗಳು',
  'past6MonthsDemand': 'ಕಳೆದ 6 ತಿಂಗಳ ಬೇಡಿಕೆ',
  'futureDemandPredictions': 'ಭವಿಷ್ಯದ ಬೇಡಿಕೆಯ ಮುನ್ಸೂಚನೆಗಳು',
  'january': 'ಜನವರಿ',
  'february': 'ಫೆಬ್ರವರಿ',
  'march': 'ಮಾರ್ಚ್',
  'april': 'ಏಪ್ರಿಲ್',
  'may': 'ಮೇ',
  'june': 'ಜೂನ್',
  'july': 'ಜುಲೈ',
  'august': 'ಆಗಸ್ಟ್',
  'september': 'ಸೆಪ್ಟೆಂಬರ್',
  'october': 'ಅಕ್ಟೋಬರ್',
  'november': 'ನವೆಂಬರ್',
  'language': 'ಭಾಷೆ',
  'noCropData': 'ಈ ರಾಜ್ಯಕ್ಕೆ ಯಾವುದೇ ಕ್ರಾಪ್ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.',
  'noPriceData': 'ಪ್ರದರ್ಶಿಸಲು ಯಾವುದೇ ಬೆಲೆ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.',
  'noDemandData': 'ಪ್ರದರ್ಶಿಸಲು ಯಾವುದೇ ಬೇಡಿಕೆ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.',
  'disease': 'ರೋಗ',
  'treatment': 'ಚಿಕಿತ್ಸೆ',
  'uploadPhoto': 'ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
  'noImageSelected': 'ಯಾವುದೇ ಚಿತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಲಾಗಿಲ್ಲ',
  'andhraPradesh': 'ಆಂಧ್ರಪ್ರದೇಶ',
  'arunachalPradesh': 'ಅರುಣಾಚಲ ಪ್ರದೇಶ',
  'assam': 'ಅಸ್ಸಾಂ',
  'bihar': 'ಬಿಹಾರ',
  'chhattisgarh': 'ಛತ್ತೀಸ್‌ಗಢ',
  'goa': 'ಗೋವಾ',
  'gujarat': 'ಗುಜರಾತ್',
  'haryana': 'ಹರಿಯಾಣ',
  'himachalPradesh': 'ಹಿಮಾಚಲ ಪ್ರದೇಶ',
  'jharkhand': 'ಜಾರ್ಖಂಡ್',
  'karnataka': 'ಕರ್ನಾಟಕ',
  'kerala': 'ಕೇರಳ',
  'madhaPradesh': 'ಮಧ್ಯಪ್ರದೇಶ',
  'maharashtra': 'ಮಹಾರಾಷ್ಟ್ರ',
  'manipur': 'ಮಣಿಪುರ',
  'meghalaya': 'ಮೇಘಾಲಯ',
  'moizoram': 'ಮಿಜೋರಾಂ',
  'nagaland': 'ನಾಗಾಲ್ಯಾಂಡ್',
  'odisha': 'ಒಡಿಶಾ',
  'punjab': 'ಪಂಜಾಬ್',
  'rajasthan': 'ರಾಜಸ್ಥಾನ',
  'sikkim': 'ಸಿಕ್ಕಿಂ',
  'tamilNadu': 'ತಮಿಳುನಾಡು',
  'telangana': 'ತೆಲಂಗಾಣ',
  'tripura': 'ತ್ರಿಪುರಾ',
  'uttarPradesh': 'ಉತ್ತರ ಪ್ರದೇಶ',
  'uttarakhand': 'ಉತ್ತರಾಖಂಡ',
  'westBengal': 'ಪಶ್ಚಿಮ ಬಂಗಾಳ',
};

Map<String, String> engToMl = {
  'almonds': 'ബദാം',
  'apple': 'ആപ്പിൾ',
  'arhar': 'അർഹർ',
  'bajra': 'ബജ്റ',
  'banana': 'വാഴപ്പഴം',
  'blackPepper': 'കറുത്ത കുരുമുളക്',
  'cashewnut': 'കശുവണ്ടി',
  'castorSeed': 'ജാതി വിത്ത്',
  'chillies': 'മുളക്',
  'coffee': 'കോഫി',
  'cottonSeed': 'പരുത്തി വിത്ത്',
  'garlic': 'വെളുത്തുള്ളി',
  'gram': 'ഗ്രാം',
  'groundnut': 'നിലക്കടല',
  'jowar': 'ജോവർ',
  'jute': 'ചണം',
  'maize': 'ചോളം',
  'masoor': 'മസൂർ',
  'moong': 'മൂംഗ്',
  'mustard': 'കടുക്',
  'onion': 'ഉള്ളി',
  'orange': 'ഓറഞ്ച്',
  'potato': 'ഉരുളക്കിഴങ്ങ്',
  'ragi': 'രാഗി',
  'soyabean': 'സോയാബീൻ',
  'sunflowerSeed': 'സൂര്യകാന്തി വിത്ത്',
  'tea': 'ചായ',
  'tomato': 'തക്കാളി',
  'urad': 'ഊരാദ്',
  'walnuts': 'വാൽനട്ട്സ്',
  'wheat': 'ഗോതമ്പ്',
  'krishiMitra': 'കൃഷി മിത്ര',
  'welcomeToKrishiMitra': 'കൃഷി മിത്രയിലേക്ക് സ്വാഗതം',
  'proceed': 'തുടരുക',
  'cropPrice': 'വിളവില',
  'cropDemand': 'വിള ആവശ്യം',
  'pestDiseaseDetection': 'കീടങ്ങളും രോഗങ്ങളും കണ്ടെത്തൽ',
  'settings': 'ക്രമീകരണങ്ങൾ',
  'selectState': 'സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
  'cropsIn': 'വിളവെടുപ്പ്',
  'thisMonth': 'ഈ മാസം',
  'nextMonth': 'അടുത്ത മാസം',
  'priceTrend': 'വില പ്രവണത',
  'demandTrend': 'ഡിമാൻഡ് ട്രെൻഡ്',
  'predictionPeriod': 'പ്രവചന കാലയളവ്',
  'next3Months': 'അടുത്ത 3 മാസം',
  'next6Months': 'അടുത്ത 6 മാസം',
  'next1Year': 'അടുത്ത 1 വർഷം',
  'past6MonthsPrices': 'കഴിഞ്ഞ 6 മാസത്തെ വിലകൾ',
  'futurePricePredictions': 'ഭാവി വില പ്രവചനങ്ങൾ',
  'past6MonthsDemand': 'കഴിഞ്ഞ 6 മാസത്തെ ആവശ്യം',
  'futureDemandPredictions': 'ഭാവി ഡിമാൻഡ് പ്രവചനങ്ങൾ',
  'january': 'ജനുവരി',
  'february': 'ഫെബ്രുവരി',
  'march': 'മാർച്ച്',
  'april': 'ഏപ്രിൽ',
  'may': 'മെയ്',
  'june': 'ജൂൺ',
  'july': 'ജൂലൈ',
  'august': 'ഓഗസ്റ്റ്',
  'september': 'സെപ്റ്റംബർ',
  'october': 'ഒക്ടോബർ',
  'november': 'നവംബർ',
  'language': 'ഭാഷ',
  'noCropData': 'ഈ സംസ്ഥാനത്തിന് ക്രോപ്പ് ഡാറ്റ ലഭ്യമല്ല.',
  'noPriceData': 'പ്രദർശിപ്പിക്കാൻ വില വിവരങ്ങളൊന്നും ലഭ്യമല്ല.',
  'noDemandData': 'പ്രദർശിപ്പിക്കാൻ ഡിമാൻഡ് ഡാറ്റ ലഭ്യമല്ല.',
  'disease': 'രോഗം',
  'treatment': 'ചികിത്സ',
  'uploadPhoto': 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
  'noImageSelected': 'ചിത്രമൊന്നും തിരഞ്ഞെടുത്തിട്ടില്ല',
  'andhraPradesh': 'ആന്ധ്രാപ്രദേശ്',
  'arunachalPradesh': 'അരുണാചൽ പ്രദേശ്',
  'assam': 'അസം',
  'bihar': 'ബീഹാർ',
  'chhattisgarh': 'ഛത്തീസ്ഗഡ്',
  'goa': 'ഗോവ',
  'gujarat': 'ഗുജറാത്ത്',
  'haryana': 'ഹരിയാന',
  'himachalPradesh': 'ഹിമാചൽ പ്രദേശ്',
  'jharkhand': 'ജാർഖണ്ഡ്',
  'karnataka': 'കർണാടക',
  'kerala': 'കേരളം',
  'madhaPradesh': 'മധ്യപ്രദേശ്',
  'maharashtra': 'മഹാരാഷ്ട്ര',
  'manipur': 'മണിപ്പൂർ',
  'meghalaya': 'മേഘാലയ',
  'moizoram': 'മിസോറാം',
  'nagaland': 'നാഗാലാൻഡ്',
  'odisha': 'ഒഡീഷ',
  'punjab': 'പഞ്ചാബ്',
  'rajasthan': 'രാജസ്ഥാൻ',
  'sikkim': 'സിക്കിം',
  'tamilNadu': 'തമിഴ്നാട്',
  'telangana': 'തെലങ്കാന',
  'tripura': 'ത്രിപുര',
  'uttarPradesh': 'ഉത്തർപ്രദേശ്',
  'uttarakhand': 'ഉത്തരാഖണ്ഡ്',
  'westBengal': 'പശ്ചിമ ബംഗാൾ',
};

Map<String, String> engToOr = {
  'almonds': 'ବାଦାମ |',
  'apple': 'ଆପଲ୍ |',
  'arhar': 'ଆରହର |',
  'bajra': 'ବାଜ୍ରା',
  'banana': 'ବାନା |',
  'blackPepper': 'କଳା ଲଙ୍କା',
  'cashewnut': 'କାଜୁନାଟ୍ |',
  'castorSeed': 'କାଷ୍ଟର ବିହନ |',
  'chillies': 'ଚିଲି',
  'coffee': 'କଫି |',
  'cottonSeed': 'କପା ବିହନ |',
  'garlic': 'ରସୁଣ |',
  'gram': 'ଗ୍ରାମ',
  'groundnut': 'ଭୂତଳ',
  'jowar': 'ଜୋୱାର୍ |',
  'jute': 'ଜଟ୍',
  'maize': 'ମକା',
  'masoor': 'ମାସୁର |',
  'moong': 'ମୁଙ୍ଗ',
  'mustard': 'ସୋରିଷ |',
  'onion': 'ପିଆଜ |',
  'orange': 'କମଳା |',
  'potato': 'ଆଳୁ |',
  'ragi': 'ରାଗି |',
  'soyabean': 'ସୋୟାବିନ୍ |',
  'sunflowerSeed': 'ସୂର୍ଯ୍ୟମୁଖୀ ବିହନ |',
  'tea': 'ଚା',
  'tomato': 'ଟମାଟୋ |',
  'urad': 'ଉରାଦ |',
  'walnuts': 'ବାଦାମ |',
  'wheat': 'ଗହମ',
  'krishiMitra': 'କୃଷ୍ଣ ମିତ୍ର',
  'welcomeToKrishiMitra': 'କୃଷ୍ଣ ମିତ୍ରଙ୍କୁ ସ୍ୱାଗତ |',
  'proceed': 'ଅଗ୍ରଗତି କର |',
  'cropPrice': 'ଫସଲ ମୂଲ୍ୟ',
  'cropDemand': 'ଫସଲ ଚାହିଦା |',
  'pestDiseaseDetection': 'କୀଟ ଏବଂ ରୋଗ ଚିହ୍ନଟ |',
  'settings': 'ସେଟିଂସମୂହ',
  'selectState': 'ରାଜ୍ୟ ଚୟନ କରନ୍ତୁ |',
  'cropsIn': 'ଫସଲ',
  'thisMonth': 'ଏହି ମାସ',
  'nextMonth': 'ପରବର୍ତ୍ତୀ ମାସ',
  'priceTrend': 'ମୂଲ୍ୟ ଟ୍ରେଣ୍ଡ |',
  'demandTrend': 'ଡିମାଣ୍ଡ ଟ୍ରେଣ୍ଡ |',
  'predictionPeriod': 'ଭବିଷ୍ୟବାଣୀ ଅବଧି',
  'next3Months': 'ପରବର୍ତ୍ତୀ 3 ମାସ |',
  'next6Months': 'ପରବର୍ତ୍ତୀ 6 ମାସ |',
  'next1Year': 'ପରବର୍ତ୍ତୀ 1 ବର୍ଷ',
  'past6MonthsPrices': 'ଗତ 6 ମାସର ମୂଲ୍ୟ |',
  'futurePricePredictions': 'ଭବିଷ୍ୟତ ମୂଲ୍ୟ ପୂର୍ବାନୁମାନ |',
  'past6MonthsDemand': 'ବିଗତ Mon ମାସର ଚାହିଦା |',
  'futureDemandPredictions': 'ଭବିଷ୍ୟତର ଚାହିଦା ପୂର୍ବାନୁମାନ |',
  'january': 'ଜାନୁଆରୀ',
  'february': 'ଫେବୃଆରୀ',
  'march': 'ମାର୍ଚ୍ଚ',
  'april': 'ଏପ୍ରିଲ୍',
  'may': 'ମେ',
  'june': 'ଜୁନ୍ |',
  'july': 'ଜୁଲାଇ',
  'august': 'ଅଗଷ୍ଟ',
  'september': 'ସେପ୍ଟେମ୍ବର |',
  'october': 'ଅକ୍ଟୋବର',
  'november': 'ନଭେମ୍ବର',
  'language': 'ଭାଷା',
  'noCropData': 'ଏହି ରାଜ୍ୟ ପାଇଁ କ crop ଣସି ଫସଲ ତଥ୍ୟ ଉପଲବ୍ଧ ନାହିଁ |',
  'noPriceData': 'ପ୍ରଦର୍ଶନ କରିବାକୁ କ price ଣସି ମୂଲ୍ୟ ତଥ୍ୟ ଉପଲବ୍ଧ ନାହିଁ |',
  'noDemandData': 'ପ୍ରଦର୍ଶନ କରିବାକୁ କ demand ଣସି ଚାହିଦା ତଥ୍ୟ ଉପଲବ୍ଧ ନାହିଁ |',
  'disease': 'ରୋଗ',
  'treatment': 'ଚିକିତ୍ସା',
  'uploadPhoto': 'ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ |',
  'noImageSelected': 'କ image ଣସି ପ୍ରତିଛବି ଚୟନ ହୋଇନାହିଁ |',
  'andhraPradesh': 'ଆନ୍ଧ୍ରପ୍ରଦେଶ',
  'arunachalPradesh': 'ଅରୁଣାଚଳ ପ୍ରଦେଶ',
  'assam': 'ଆସାମ |',
  'bihar': 'ବିହାର |',
  'chhattisgarh': 'ଛତିଶଗଡ',
  'goa': 'ଗୋଆ',
  'gujarat': 'ଗୁଜୁରାଟ',
  'haryana': 'ହରିୟାଣା',
  'himachalPradesh': 'ହିମାଚଳ ପ୍ରଦେଶ',
  'jharkhand': 'H ାଡଖଣ୍ଡ',
  'karnataka': 'କର୍ଣ୍ଣାଟକ',
  'kerala': 'କେରଳ',
  'madhaPradesh': 'ମଧ୍ୟପ୍ରଦେଶ',
  'maharashtra': 'ମହାରାଷ୍ଟ୍ର',
  'manipur': 'ମଣିପୁର',
  'meghalaya': 'ମେଘାଳୟ',
  'moizoram': 'ମିଜୋରାମ',
  'nagaland': 'ନାଗାଲାଣ୍ଡ |',
  'odisha': 'ଓଡ଼ିଶା',
  'punjab': 'ପଞ୍ଜାବ',
  'rajasthan': 'ରାଜସ୍ଥାନ',
  'sikkim': 'ସିକ୍କିମ୍ |',
  'tamilNadu': 'ତାମିଲନାଡୁ |',
  'telangana': 'ତେଲେଙ୍ଗାନା',
  'tripura': 'ତ୍ରିପୁରା',
  'uttarPradesh': 'ଉତ୍ତରପ୍ରଦେଶ',
  'uttarakhand': 'ଉତ୍ତରାଖଣ୍ଡ',
  'westBengal': 'ପଶ୍ଚିମବଙ୍ଗ',
};

